name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  CI:
    name: Checking code quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        pnpm-version: [9]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Cache pnpm dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Lint
        run: npx nx run-many --target=lint

      - name: Type check
        run: npx nx run-many --target=type-check

      - name: Build
        run: npx nx run-many --target=build

      - name: Test
        run: npx nx run-many --target=test --parallel=1

      - name: Test e2e
        run: npx nx run-many --target=test:e2e --parallel=1
